//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DoenaSoft.DVDProfiler.EnhancedNotes
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedNotes
    {

        private Text note1Field;

        private Text note2Field;

        private Text note3Field;

        private Text note4Field;

        private Text note5Field;

        private InvelosData invelosDataField;

        /// <remarks/>
        public Text Note1
        {
            get
            {
                return this.note1Field;
            }
            set
            {
                this.note1Field = value;
            }
        }

        /// <remarks/>
        public Text Note2
        {
            get
            {
                return this.note2Field;
            }
            set
            {
                this.note2Field = value;
            }
        }

        /// <remarks/>
        public Text Note3
        {
            get
            {
                return this.note3Field;
            }
            set
            {
                this.note3Field = value;
            }
        }

        /// <remarks/>
        public Text Note4
        {
            get
            {
                return this.note4Field;
            }
            set
            {
                this.note4Field = value;
            }
        }

        /// <remarks/>
        public Text Note5
        {
            get
            {
                return this.note5Field;
            }
            set
            {
                this.note5Field = value;
            }
        }

        /// <remarks/>
        public InvelosData InvelosData
        {
            get
            {
                return this.invelosDataField;
            }
            set
            {
                this.invelosDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Text
    {

        private string displayNameField;

        private string base64DisplayNameField;

        private bool isHtmlField;

        private string base64NoteField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64DisplayName
        {
            get
            {
                return this.base64DisplayNameField;
            }
            set
            {
                this.base64DisplayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.isHtmlField;
            }
            set
            {
                this.isHtmlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64Note
        {
            get
            {
                return this.base64NoteField;
            }
            set
            {
                this.base64NoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile
    {

        private EnhancedNotes enhancedNotesField;

        private string idField;

        private string titleField;

        /// <remarks/>
        public EnhancedNotes EnhancedNotes
        {
            get
            {
                return this.enhancedNotesField;
            }
            set
            {
                this.enhancedNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvelosData
    {

        private string notesField;

        /// <remarks/>
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedNotesList
    {

        private Profile[] profilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Profile[] Profiles
        {
            get
            {
                return this.profilesField;
            }
            set
            {
                this.profilesField = value;
            }
        }
    }
}